- repo: local
  hooks:
    - id: gpt-commit-message
      name: GPT Commit Message
      entry: python {{cookiecutter.project_slug}}/scripts/gpt_commit.py
      language: python
      additional_dependencies: [openai]
      stages: [prepare-commit-msg]
      args: [.git/COMMIT_EDITMSG]
      pass_filenames: false