# .pre-commit-hooks.yaml
-   id: gpt-commit-message
    name: GPT Commit Message
    description: >
      Generate a Conventional Commit message from your staged diff
      using OpenAI’s GPT.
    entry: gpt-commit-message              # must match your console_scripts name
    language: python
    pass_filenames: false
    stages: [prepare-commit-msg]
    additional_dependencies: [openai>=0.27.0]
