repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files

-   repo: local
    hooks:
    -   id: gpt-commit-message
        name: GPT Commit Message
        entry: python {{cookiecutter.project_slug}}/scripts/gpt_commit.py
        language: python
        additional_dependencies: [openai]
        stages: [prepare-commit-msg]
        args: [.git/COMMIT_EDITMSG]
        pass_filenames: false

default_install_hook_types: [pre-commit, prepare-commit-msg]
default_stages: [pre-commit, pre-merge-commit]
